/**
 * AIRE Document Generator
 * Generates pre-filled Louisiana LREC form PDFs using pdf-lib.
 * Phase 1: Programmatic PDF generation (no template files needed).
 * Phase 2 (future): Fill actual LREC fillable PDF templates.
 */

import { PDFDocument, StandardFonts, rgb, PDFPage, PDFFont } from "pdf-lib";

export interface DocumentFields {
  // Common fields across all LREC forms
  propertyAddress?: string;
  propertyCity?: string;
  propertyState?: string;
  propertyZip?: string;
  parish?: string;
  buyerName?: string;
  sellerName?: string;
  agentName?: string;
  agentLicense?: string;
  brokerageName?: string;
  contractDate?: string;
  closingDate?: string;
  purchasePrice?: string;
  earnestMoney?: string;

  // Addendum-specific
  addendumType?: string;
  addendumText?: string;
  repairItems?: string[];
  conditions?: string[];

  // Inspection response
  inspectionDate?: string;
  inspectionFindings?: string;
  repairRequest?: string;
  repairDeadline?: string;

  // Generic key-value for any field
  [key: string]: string | string[] | undefined;
}

export interface GeneratedPDF {
  buffer: Buffer;
  filename: string;
  pageCount: number;
  documentType: string;
  fields: DocumentFields;
}

// ─── PDF Layout Constants ───────────────────────────────────────

const MARGIN = 50;
const LINE_HEIGHT = 18;
const HEADER_SIZE = 16;
const SUBHEADER_SIZE = 12;
const BODY_SIZE = 10;
const FIELD_LABEL_SIZE = 8;

const COLOR_BLACK = rgb(0, 0, 0);
const COLOR_GRAY = rgb(0.4, 0.4, 0.4);
const COLOR_SAGE = rgb(0.604, 0.671, 0.494); // #9aab7e

// ─── Helpers ────────────────────────────────────────────────────

function drawField(
  page: PDFPage,
  font: PDFFont,
  boldFont: PDFFont,
  label: string,
  value: string | undefined,
  x: number,
  y: number,
  maxWidth: number = 250
): number {
  // Label
  page.drawText(label, {
    x,
    y,
    size: FIELD_LABEL_SIZE,
    font,
    color: COLOR_GRAY,
  });
  // Value (or underline placeholder)
  const valText = value || "________________________";
  page.drawText(valText, {
    x,
    y: y - 14,
    size: BODY_SIZE,
    font: value ? boldFont : font,
    color: COLOR_BLACK,
    maxWidth,
  });
  return y - 36; // Return next Y position
}

function drawSectionHeader(
  page: PDFPage,
  font: PDFFont,
  text: string,
  y: number
): number {
  page.drawText(text, {
    x: MARGIN,
    y,
    size: SUBHEADER_SIZE,
    font,
    color: COLOR_SAGE,
  });
  // Underline
  page.drawLine({
    start: { x: MARGIN, y: y - 4 },
    end: { x: 560, y: y - 4 },
    thickness: 0.5,
    color: COLOR_SAGE,
  });
  return y - 24;
}

// ─── Document Generators ────────────────────────────────────────

/**
 * Generate a Louisiana Purchase Agreement (LREC-001) draft PDF.
 */
export async function generatePurchaseAgreement(
  fields: DocumentFields
): Promise<GeneratedPDF> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const page = pdfDoc.addPage([612, 792]); // Letter size
  let y = 740;

  // Header
  page.drawText("LOUISIANA RESIDENTIAL AGREEMENT TO BUY OR SELL", {
    x: MARGIN,
    y,
    size: HEADER_SIZE,
    font: boldFont,
    color: COLOR_BLACK,
  });
  y -= 20;
  page.drawText("DRAFT — Generated by AIRE Intelligence", {
    x: MARGIN,
    y,
    size: BODY_SIZE,
    font,
    color: COLOR_SAGE,
  });
  y -= 8;
  page.drawText(`Generated: ${new Date().toLocaleDateString("en-US")}`, {
    x: MARGIN,
    y,
    size: FIELD_LABEL_SIZE,
    font,
    color: COLOR_GRAY,
  });
  y -= 30;

  // Section 1: Property
  y = drawSectionHeader(page, boldFont, "1. PROPERTY INFORMATION", y);
  const col1 = MARGIN;
  const col2 = 310;

  y = drawField(page, font, boldFont, "Property Address", fields.propertyAddress, col1, y);
  let y2 = drawField(page, font, boldFont, "Parish", fields.parish || "East Baton Rouge", col2, y + 36);
  y = Math.min(y, y2);

  y = drawField(page, font, boldFont, "City", fields.propertyCity || "Baton Rouge", col1, y);
  y2 = drawField(page, font, boldFont, "State / Zip", `${fields.propertyState || "LA"} ${fields.propertyZip || ""}`.trim(), col2, y + 36);
  y = Math.min(y, y2);

  // Section 2: Parties
  y -= 10;
  y = drawSectionHeader(page, boldFont, "2. PARTIES", y);
  y = drawField(page, font, boldFont, "Buyer", fields.buyerName, col1, y);
  y2 = drawField(page, font, boldFont, "Seller", fields.sellerName, col2, y + 36);
  y = Math.min(y, y2);

  // Section 3: Price & Terms
  y -= 10;
  y = drawSectionHeader(page, boldFont, "3. PRICE AND TERMS", y);
  y = drawField(page, font, boldFont, "Purchase Price", fields.purchasePrice, col1, y);
  y2 = drawField(page, font, boldFont, "Earnest Money", fields.earnestMoney, col2, y + 36);
  y = Math.min(y, y2);

  // Section 4: Key Dates
  y -= 10;
  y = drawSectionHeader(page, boldFont, "4. KEY DATES", y);
  y = drawField(page, font, boldFont, "Contract Date", fields.contractDate, col1, y);
  y2 = drawField(page, font, boldFont, "Closing Date", fields.closingDate, col2, y + 36);
  y = Math.min(y, y2);

  // Section 5: Agent Info
  y -= 10;
  y = drawSectionHeader(page, boldFont, "5. AGENT / BROKERAGE", y);
  y = drawField(page, font, boldFont, "Agent Name", fields.agentName, col1, y);
  y2 = drawField(page, font, boldFont, "License #", fields.agentLicense, col2, y + 36);
  y = Math.min(y, y2);
  y = drawField(page, font, boldFont, "Brokerage", fields.brokerageName, col1, y);

  // Footer
  page.drawText("This is a DRAFT document generated by AIRE Intelligence. Not legally binding until executed by all parties.", {
    x: MARGIN,
    y: 40,
    size: 7,
    font,
    color: COLOR_GRAY,
    maxWidth: 512,
  });

  const pdfBytes = await pdfDoc.save();
  const address = fields.propertyAddress || "Unknown";
  return {
    buffer: Buffer.from(pdfBytes),
    filename: `LREC-001_Purchase_Agreement_${address.replace(/[^a-zA-Z0-9]/g, "_")}.pdf`,
    pageCount: 1,
    documentType: "purchase_agreement",
    fields,
  };
}

/**
 * Generate a general Addendum (LREC-103 style) draft PDF.
 */
export async function generateAddendum(
  fields: DocumentFields
): Promise<GeneratedPDF> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const page = pdfDoc.addPage([612, 792]);
  let y = 740;

  // Header
  page.drawText("ADDENDUM TO PURCHASE AGREEMENT", {
    x: MARGIN,
    y,
    size: HEADER_SIZE,
    font: boldFont,
    color: COLOR_BLACK,
  });
  y -= 20;
  page.drawText("DRAFT — Generated by AIRE Intelligence", {
    x: MARGIN,
    y,
    size: BODY_SIZE,
    font,
    color: COLOR_SAGE,
  });
  y -= 30;

  // Reference
  y = drawSectionHeader(page, boldFont, "REFERENCE", y);
  y = drawField(page, font, boldFont, "Property Address", fields.propertyAddress, MARGIN, y, 460);
  y = drawField(page, font, boldFont, "Buyer", fields.buyerName, MARGIN, y, 220);
  y = drawField(page, font, boldFont, "Seller", fields.sellerName, 310, y + 36, 220);
  y -= 10;
  y = drawField(page, font, boldFont, "Contract Date", fields.contractDate, MARGIN, y, 220);

  // Addendum Content
  y -= 20;
  y = drawSectionHeader(page, boldFont, "ADDENDUM TERMS", y);

  const addendumType = fields.addendumType || "General Addendum";
  page.drawText(`Type: ${addendumType}`, {
    x: MARGIN,
    y,
    size: BODY_SIZE,
    font: boldFont,
    color: COLOR_BLACK,
  });
  y -= LINE_HEIGHT * 1.5;

  // Addendum body text
  const bodyText = fields.addendumText || "The parties agree to the following additional terms and conditions:";
  const lines = wrapText(bodyText, font, BODY_SIZE, 512);
  for (const line of lines) {
    if (y < 80) break;
    page.drawText(line, {
      x: MARGIN,
      y,
      size: BODY_SIZE,
      font,
      color: COLOR_BLACK,
    });
    y -= LINE_HEIGHT;
  }

  // Repair items (if inspection response)
  if (fields.repairItems && fields.repairItems.length > 0) {
    y -= 10;
    y = drawSectionHeader(page, boldFont, "REPAIR ITEMS", y);
    for (let i = 0; i < fields.repairItems.length; i++) {
      if (y < 80) break;
      page.drawText(`${i + 1}. ${fields.repairItems[i]}`, {
        x: MARGIN + 10,
        y,
        size: BODY_SIZE,
        font,
        color: COLOR_BLACK,
        maxWidth: 500,
      });
      y -= LINE_HEIGHT;
    }
  }

  // Signature lines
  y = Math.min(y, 180);
  y -= 20;
  page.drawLine({ start: { x: MARGIN, y }, end: { x: 260, y }, thickness: 0.5, color: COLOR_BLACK });
  page.drawText("Buyer Signature / Date", { x: MARGIN, y: y - 12, size: FIELD_LABEL_SIZE, font, color: COLOR_GRAY });

  page.drawLine({ start: { x: 310, y }, end: { x: 560, y }, thickness: 0.5, color: COLOR_BLACK });
  page.drawText("Seller Signature / Date", { x: 310, y: y - 12, size: FIELD_LABEL_SIZE, font, color: COLOR_GRAY });

  // Footer
  page.drawText("DRAFT — Not legally binding until executed by all parties. Generated by AIRE Intelligence.", {
    x: MARGIN,
    y: 40,
    size: 7,
    font,
    color: COLOR_GRAY,
    maxWidth: 512,
  });

  const pdfBytes = await pdfDoc.save();
  const address = fields.propertyAddress || "Unknown";
  return {
    buffer: Buffer.from(pdfBytes),
    filename: `Addendum_${addendumType.replace(/[^a-zA-Z0-9]/g, "_")}_${address.replace(/[^a-zA-Z0-9]/g, "_")}.pdf`,
    pageCount: 1,
    documentType: "addendum",
    fields,
  };
}

/**
 * Generate an Inspection Response (LREC repair request) draft PDF.
 */
export async function generateInspectionResponse(
  fields: DocumentFields
): Promise<GeneratedPDF> {
  // Reuse addendum generator with inspection-specific framing
  const inspectionFields: DocumentFields = {
    ...fields,
    addendumType: "Inspection Response / Repair Request",
    addendumText: fields.repairRequest ||
      `Following the property inspection conducted on ${fields.inspectionDate || "[DATE]"}, ` +
      `Buyer requests the following repairs be completed prior to closing:`,
  };

  if (fields.inspectionFindings && !fields.repairItems) {
    inspectionFields.repairItems = fields.inspectionFindings
      .split(/[;\n]/)
      .map((s) => s.trim())
      .filter(Boolean);
  }

  const result = await generateAddendum(inspectionFields);
  result.documentType = "inspection_response";
  result.filename = result.filename.replace("Addendum_", "Inspection_Response_");
  return result;
}

/**
 * Route to the correct generator based on document type.
 */
export async function generateDocument(
  type: string,
  fields: DocumentFields
): Promise<GeneratedPDF> {
  switch (type) {
    case "purchase_agreement":
      return generatePurchaseAgreement(fields);
    case "inspection_response":
      return generateInspectionResponse(fields);
    case "addendum":
    case "condominium_addendum":
    case "deposit_addendum":
    case "new_construction_addendum":
    case "historic_district_addendum":
    case "private_sewerage_addendum":
      return generateAddendum({ ...fields, addendumType: type.replace(/_/g, " ") });
    default:
      return generateAddendum({ ...fields, addendumType: type.replace(/_/g, " ") });
  }
}

// ─── Text Wrapping Utility ──────────────────────────────────────

function wrapText(
  text: string,
  font: PDFFont,
  fontSize: number,
  maxWidth: number
): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let currentLine = "";

  for (const word of words) {
    const testLine = currentLine ? `${currentLine} ${word}` : word;
    const width = font.widthOfTextAtSize(testLine, fontSize);
    if (width > maxWidth && currentLine) {
      lines.push(currentLine);
      currentLine = word;
    } else {
      currentLine = testLine;
    }
  }
  if (currentLine) lines.push(currentLine);
  return lines;
}
