"use client"

import { useState, useRef } from "react"
import { FeedbackButtons } from "@/components/FeedbackButtons"

interface Transaction {
  id: string
  propertyAddress: string
  status: string
}

interface FilledField {
  fieldNumber: number | string
  name: string
  section: string
  value: string | number | boolean | null
  confidence: "high" | "medium" | "low"
  source: string
  transactionField?: string
  options?: string[]
  type: string
}

interface MissingField {
  fieldNumber: number | string
  name: string
  section: string
  type: string
  options?: string[]
  transactionField?: string
}

interface AutoFillResult {
  filled: FilledField[]
  missing: MissingField[]
  totalRequired: number
  totalFilled: number
  completionPct: number
}

const SECTION_LABELS: Record<string, string> = {
  location: "Location",
  property_details: "Property Details",
  features: "Features",
  agent_info: "Agent Info",
}

const DOC_TYPES = [
  { value: "appraisal", label: "Appraisal" },
  { value: "old_listing", label: "Old Listing" },
  { value: "property_disclosure", label: "Property Disclosure" },
  { value: "other", label: "Other Document" },
]

export function MLSAutoFillWizard({ transactions }: { transactions: Transaction[] }) {
  const [step, setStep] = useState(1)
  const [docType, setDocType] = useState("appraisal")
  const [selectedTxn, setSelectedTxn] = useState("")
  const [file, setFile] = useState<File | null>(null)
  const [uploading, setUploading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [result, setResult] = useState<AutoFillResult | null>(null)
  const [manualValues, setManualValues] = useState<Record<string, string>>({})
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)
  const fileRef = useRef<HTMLInputElement>(null)

  async function handleUpload() {
    if (!file) return
    setUploading(true)
    setError(null)
    try {
      const formData = new FormData()
      formData.append("file", file)
      formData.append("documentType", docType)
      if (selectedTxn) formData.append("transactionId", selectedTxn)

      const res = await fetch("/api/mls/autofill", { method: "POST", body: formData })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || "Failed to extract fields")

      setResult(data.result)
      setSaved(!!data.saved)
      setStep(2)
    } catch (e) {
      setError(e instanceof Error ? e.message : "Upload failed")
    } finally {
      setUploading(false)
    }
  }

  function handleManualChange(fieldNumber: string, value: string) {
    setManualValues(prev => ({ ...prev, [fieldNumber]: value }))
  }

  async function handleSaveToTransaction() {
    if (!selectedTxn || !result) return
    setSaving(true)
    setError(null)
    try {
      // Build update payload from filled + manual values
      const update: Record<string, unknown> = {}
      for (const f of result.filled) {
        if (f.transactionField) update[f.transactionField] = f.value
      }
      for (const m of result.missing) {
        const val = manualValues[String(m.fieldNumber)]
        if (val && m.transactionField) update[m.transactionField] = val
      }
      update.mlsSource = docType === "appraisal" ? "APPRAISAL_EXTRACT" : "OLD_LISTING"
      update.mlsLastSyncedAt = new Date().toISOString()

      const res = await fetch(`/api/transactions/${selectedTxn}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(update),
      })
      if (!res.ok) throw new Error("Failed to save to transaction")
      setSaved(true)
    } catch (e) {
      setError(e instanceof Error ? e.message : "Save failed")
    } finally {
      setSaving(false)
    }
  }

  function handleDownloadSheet() {
    if (!result) return
    const lines: string[] = [
      "PARAGON MLS INPUT SHEET",
      "Generated by AIRE " + new Date().toLocaleDateString(),
      "=" .repeat(60),
      "",
    ]

    for (const section of ["location", "property_details", "features", "agent_info"] as const) {
      lines.push(`--- ${SECTION_LABELS[section]} ---`)
      const sectionFilled = result.filled.filter(f => f.section === section)
      const sectionMissing = result.missing.filter(f => f.section === section)
      for (const f of sectionFilled) {
        const conf = f.confidence === "high" ? "" : ` [${f.confidence}]`
        lines.push(`  [${f.fieldNumber}] ${f.name}: ${f.value}${conf}`)
      }
      for (const m of sectionMissing) {
        const manual = manualValues[String(m.fieldNumber)]
        if (manual) {
          lines.push(`  [${m.fieldNumber}] ${m.name}: ${manual} [manual]`)
        } else {
          lines.push(`  [${m.fieldNumber}] ${m.name}: ________ (MISSING)`)
        }
      }
      lines.push("")
    }

    lines.push(`Completion: ${result.completionPct}% (${result.totalFilled}/${result.totalRequired} required fields)`)

    const blob = new Blob([lines.join("\n")], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `MLS-Input-Sheet-${new Date().toISOString().slice(0, 10)}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  // ── Step 1: Upload ──
  if (step === 1) {
    return (
      <div className="space-y-6">
        {/* Document type */}
        <div className="border border-brown-border rounded-xl p-6">
          <label className="block text-cream text-sm font-medium mb-3">Document Type</label>
          <div className="flex flex-wrap gap-2">
            {DOC_TYPES.map(dt => (
              <button
                key={dt.value}
                onClick={() => setDocType(dt.value)}
                className={`px-4 py-2 rounded-lg text-sm transition-colors ${
                  docType === dt.value
                    ? "bg-copper text-cream"
                    : "bg-warm/10 text-cream-dim hover:bg-warm/20"
                }`}
              >
                {dt.label}
              </button>
            ))}
          </div>
        </div>

        {/* Transaction picker */}
        {transactions.length > 0 && (
          <div className="border border-brown-border rounded-xl p-6">
            <label className="block text-cream text-sm font-medium mb-3">
              Link to Transaction <span className="text-cream-dim/40">(optional)</span>
            </label>
            <select
              value={selectedTxn}
              onChange={e => setSelectedTxn(e.target.value)}
              className="w-full bg-dark-card border border-brown-border rounded-lg px-3 py-2 text-cream text-sm focus:outline-none focus:border-warm/40"
            >
              <option value="">None — extract only</option>
              {transactions.map(t => (
                <option key={t.id} value={t.id}>
                  {t.propertyAddress} ({t.status.replace(/_/g, " ").toLowerCase()})
                </option>
              ))}
            </select>
          </div>
        )}

        {/* File upload */}
        <div className="border border-brown-border rounded-xl p-6">
          <label className="block text-cream text-sm font-medium mb-3">Upload PDF</label>
          <input
            ref={fileRef}
            type="file"
            accept=".pdf"
            onChange={e => setFile(e.target.files?.[0] || null)}
            className="hidden"
          />
          <div
            onClick={() => fileRef.current?.click()}
            className="border-2 border-dashed border-brown-border/50 rounded-xl p-10 text-center cursor-pointer hover:border-warm/30 transition-colors"
          >
            {file ? (
              <div>
                <p className="text-cream text-sm font-medium">{file.name}</p>
                <p className="text-cream-dim/40 text-xs mt-1">{(file.size / 1024).toFixed(0)} KB</p>
              </div>
            ) : (
              <div>
                <p className="text-cream-dim/60 text-sm">Click to select a PDF</p>
                <p className="text-cream-dim/30 text-xs mt-1">Appraisal, old MLS listing, or disclosure</p>
              </div>
            )}
          </div>
        </div>

        {error && (
          <div className="border border-red-500/30 bg-red-500/5 rounded-xl p-4 text-red-400 text-sm">
            {error}
          </div>
        )}

        <button
          onClick={handleUpload}
          disabled={!file || uploading}
          className="w-full bg-copper text-cream py-3 rounded-xl text-sm font-medium hover:bg-copper/90 transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
        >
          {uploading ? "Extracting fields..." : "Extract MLS Fields"}
        </button>
      </div>
    )
  }

  // ── Step 2+: Results ──
  if (!result) return null

  return (
    <div className="space-y-6">
      {/* Completion header */}
      <div className="border border-brown-border rounded-xl p-6">
        <div className="flex items-center justify-between mb-4">
          <h2 className="font-[family-name:var(--font-cormorant)] italic text-cream text-xl">
            Extraction Results
          </h2>
          <span className={`font-mono text-sm px-3 py-1 rounded-full ${
            result.completionPct >= 80 ? "bg-green-500/15 text-green-400" :
            result.completionPct >= 50 ? "bg-yellow-500/15 text-yellow-400" :
            "bg-red-500/15 text-red-400"
          }`}>
            {result.completionPct}% complete
          </span>
        </div>
        <div className="w-full bg-warm/10 rounded-full h-2">
          <div
            className={`h-2 rounded-full transition-all ${
              result.completionPct >= 80 ? "bg-green-500/60" :
              result.completionPct >= 50 ? "bg-yellow-500/60" :
              "bg-red-500/60"
            }`}
            style={{ width: `${result.completionPct}%` }}
          />
        </div>
        <p className="text-cream-dim/40 text-xs mt-2">
          {result.totalFilled} of {result.totalRequired} required fields filled
        </p>
        <div className="flex justify-end mt-3">
          <FeedbackButtons
            feature="mls_autofill"
            metadata={{ completionPct: result.completionPct, totalFilled: result.totalFilled, totalRequired: result.totalRequired }}
            className="[&_span]:text-cream-dim/40 [&_button]:text-cream-dim/40 [&_button:hover]:text-green-400 [&_button:last-child:hover]:text-red-400"
          />
        </div>
      </div>

      {/* Fields by section */}
      {(["location", "property_details", "features", "agent_info"] as const).map(section => {
        const sectionFilled = result.filled.filter(f => f.section === section)
        const sectionMissing = result.missing.filter(f => f.section === section)
        if (sectionFilled.length === 0 && sectionMissing.length === 0) return null

        return (
          <div key={section} className="border border-brown-border rounded-xl p-6">
            <h3 className="text-cream text-sm font-medium mb-4">{SECTION_LABELS[section]}</h3>
            <div className="space-y-2">
              {/* Filled fields */}
              {sectionFilled.map(f => (
                <div
                  key={String(f.fieldNumber)}
                  className="flex items-center justify-between py-2 px-3 rounded-lg bg-green-500/5 border border-green-500/10"
                >
                  <div className="flex items-center gap-3 min-w-0 flex-1">
                    <span className="font-mono text-[10px] text-cream-dim/30 w-8 shrink-0">
                      {f.fieldNumber}
                    </span>
                    <span className="text-cream text-sm truncate">{f.name}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-cream text-sm font-medium truncate max-w-[200px]">
                      {String(f.value)}
                    </span>
                    <span className={`text-[9px] px-1.5 py-0.5 rounded-full ${
                      f.confidence === "high" ? "bg-green-500/15 text-green-400" :
                      f.confidence === "medium" ? "bg-yellow-500/15 text-yellow-400" :
                      "bg-red-500/15 text-red-400"
                    }`}>
                      {f.confidence}
                    </span>
                  </div>
                </div>
              ))}

              {/* Missing fields */}
              {sectionMissing.map(m => (
                <div
                  key={String(m.fieldNumber)}
                  className="flex items-center justify-between py-2 px-3 rounded-lg bg-red-500/5 border border-red-500/10"
                >
                  <div className="flex items-center gap-3 min-w-0 flex-1">
                    <span className="font-mono text-[10px] text-cream-dim/30 w-8 shrink-0">
                      {m.fieldNumber}
                    </span>
                    <span className="text-cream-dim/60 text-sm">{m.name}</span>
                  </div>
                  <div className="w-48">
                    {m.options ? (
                      <select
                        value={manualValues[String(m.fieldNumber)] || ""}
                        onChange={e => handleManualChange(String(m.fieldNumber), e.target.value)}
                        className="w-full bg-dark-card border border-brown-border rounded px-2 py-1 text-cream text-xs focus:outline-none focus:border-warm/40"
                      >
                        <option value="">Select...</option>
                        {m.options.map(o => (
                          <option key={o} value={o}>{o}</option>
                        ))}
                      </select>
                    ) : (
                      <input
                        type={m.type === "number" || m.type === "decimal" ? "number" : "text"}
                        step={m.type === "decimal" ? "0.01" : undefined}
                        value={manualValues[String(m.fieldNumber)] || ""}
                        onChange={e => handleManualChange(String(m.fieldNumber), e.target.value)}
                        placeholder={m.name}
                        className="w-full bg-dark-card border border-brown-border rounded px-2 py-1 text-cream text-xs focus:outline-none focus:border-warm/40 placeholder:text-cream-dim/20"
                      />
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )
      })}

      {error && (
        <div className="border border-red-500/30 bg-red-500/5 rounded-xl p-4 text-red-400 text-sm">
          {error}
        </div>
      )}

      {saved && (
        <div className="border border-green-500/30 bg-green-500/5 rounded-xl p-4 text-green-400 text-sm">
          Fields saved to transaction successfully.
        </div>
      )}

      {/* Action buttons */}
      <div className="flex flex-wrap gap-3">
        <button
          onClick={handleDownloadSheet}
          className="flex-1 bg-warm/15 text-warm py-3 rounded-xl text-sm font-medium hover:bg-warm/25 transition-colors"
        >
          Generate MLS Input Sheet
        </button>

        {selectedTxn && !saved && (
          <button
            onClick={handleSaveToTransaction}
            disabled={saving}
            className="flex-1 bg-copper text-cream py-3 rounded-xl text-sm font-medium hover:bg-copper/90 transition-colors disabled:opacity-40"
          >
            {saving ? "Saving..." : "Save to Transaction"}
          </button>
        )}

        <button
          onClick={() => { setStep(1); setResult(null); setFile(null); setManualValues({}); setSaved(false) }}
          className="px-6 bg-warm/10 text-cream-dim py-3 rounded-xl text-sm hover:bg-warm/15 transition-colors"
        >
          Start Over
        </button>
      </div>
    </div>
  )
}
