/**
 * POST /api/contracts/autofill
 * Takes deal data + agent profile → generates pre-filled LREC PDF.
 * The agent only provides: address, price, dates, financing, parties.
 * Everything else (agent info, brokerage, license, LA defaults) is auto-filled.
 */

import { NextRequest, NextResponse } from "next/server"
import { auth } from "@clerk/nextjs/server"
import prisma from "@/lib/prisma"
import { PDFDocument, StandardFonts, rgb } from "pdf-lib"
import { AGENT_PROFILE, buildAutoFillData } from "@/lib/contracts/agent-profile"
import { LREC_101, LREC_102, type FormDefinition } from "@/lib/contracts/lrec-fields"

const FORM_MAP: Record<string, FormDefinition> = {
  "lrec-101": LREC_101,
  "lrec-102": LREC_102,
}

export async function POST(req: NextRequest) {
  const { userId } = await auth()
  if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const body = await req.json()
  const { formId = "lrec-101", transactionId, deal } = body

  const formDef = FORM_MAP[formId]
  if (!formDef) {
    return NextResponse.json({ error: `Unknown form: ${formId}` }, { status: 400 })
  }

  // If transactionId provided, pull deal data from DB
  let dealData = deal || {}
  if (transactionId) {
    const txn = await prisma.transaction.findUnique({
      where: { id: transactionId },
    })
    if (txn) {
      dealData = {
        address: txn.propertyAddress,
        city: txn.propertyCity || undefined,
        state: txn.propertyState || "LA",
        zip: txn.propertyZip || undefined,
        mlsNumber: txn.mlsNumber || undefined,
        buyerName: txn.buyerName || undefined,
        buyerEmail: txn.buyerEmail || undefined,
        buyerPhone: txn.buyerPhone || undefined,
        sellerName: txn.sellerName || undefined,
        sellerEmail: txn.sellerEmail || undefined,
        sellerPhone: txn.sellerPhone || undefined,
        purchasePrice: txn.acceptedPrice || txn.listPrice || undefined,
        contractDate: txn.contractDate?.toISOString().split("T")[0] || undefined,
        closingDate: txn.closingDate?.toISOString().split("T")[0] || undefined,
        titleCompany: txn.titleCompany || undefined,
        ...dealData, // allow overrides
      }
    }
  }

  // Build auto-fill field values
  const fieldValues = buildAutoFillData(AGENT_PROFILE, dealData)

  // Generate PDF
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
  const fontSize = 9
  const headerSize = 14

  for (let pageNum = 1; pageNum <= formDef.pages; pageNum++) {
    const page = pdfDoc.addPage([612, 792]) // Letter size
    const { height } = page.getSize()

    // Header
    page.drawText(formDef.title.toUpperCase(), {
      x: 72,
      y: height - 50,
      size: headerSize,
      font: fontBold,
      color: rgb(0.12, 0.14, 0.09),
    })

    // Form number + page
    page.drawText(`${formDef.formNumber} (${formDef.revision}) — Page ${pageNum} of ${formDef.pages}`, {
      x: 72,
      y: height - 68,
      size: 7,
      font,
      color: rgb(0.4, 0.5, 0.3),
    })

    // Draw fields for this page
    const pageFields = formDef.fields.filter(f => f.page === pageNum)
    for (const field of pageFields) {
      const x = (field.xPercent / 100) * 612
      const y = height - (field.yPercent / 100) * 792
      const w = (field.widthPercent / 100) * 612
      const h = (field.heightPercent / 100) * 792

      // Field label
      page.drawText(field.label, {
        x,
        y: y + 2,
        size: 6.5,
        font,
        color: rgb(0.4, 0.5, 0.3),
      })

      // Field value (auto-filled)
      const value = fieldValues[field.id] || ""
      if (value) {
        page.drawText(value, {
          x,
          y: y - 10,
          size: fontSize,
          font: fontBold,
          color: rgb(0.12, 0.14, 0.09),
          maxWidth: w,
        })
      }

      // Underline
      page.drawLine({
        start: { x, y: y - 13 },
        end: { x: x + w, y: y - 13 },
        thickness: 0.5,
        color: rgb(0.7, 0.75, 0.65),
      })
    }

    // Footer
    page.drawText("Generated by AIRE Intelligence — aireintel.org", {
      x: 72,
      y: 30,
      size: 6,
      font,
      color: rgb(0.6, 0.65, 0.5),
    })
  }

  const pdfBytes = await pdfDoc.save()
  const pdfBuffer = Buffer.from(pdfBytes)

  // Count how many fields were auto-filled
  const filledCount = Object.values(fieldValues).filter(v => v).length
  const totalFields = formDef.fields.length

  return new NextResponse(pdfBuffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="${formDef.formNumber}-${dealData.address || "contract"}.pdf"`,
      "X-Fields-Filled": String(filledCount),
      "X-Fields-Total": String(totalFields),
    },
  })
}
